### ISSUE TITLE
Typo in aries-cli message

### ISSUE THREAD

**Issue by janrtvld** [animo/aries-cli#137]
Should be `existing connection`

<img width="556" alt="image" src="https://user-images.githubusercontent.com/60812202/161441216-2ce5e405-21e8-4019-888c-ec708cf5ee96.png">

**Comment by janrtvld** [comment]
Any reason why this one is `aries-cli message` single and not plural?

**Comment by blu3beri** [comment]
@janrtvld everything will be singular from now on.
