### ISSUE TITLE
Rename workflow to automation in file paths for consistency.

### ISSUE THREAD

**Issue by anagoessens** [animo/aries-cli#143]
**Describe your new idea or enhancement**

Even though we renamed the feature, the files and messages are still called workflow. (see workflow/src/workflows/credential_offer.rs)

I propose to change them for consistency. I started the process but didn't want to mess up anything.

**Comment by blu3beri** [comment]
I kept them intentionally as workflow as they are workflows and externally we did not want to call it that. I am not opposed to changing it, but I dont think we have to.
