### ISSUE TITLE
Binary for MacOS (apple-x86_64) seems to be corrupt/incompatible

### ISSUE THREAD

**Issue by tdiesler** [animo/aries-cli#159]
**Describe the bug**

`apple-x86_64-aries-cli` seems to be corrupt or incompatible. When I open it I see ...

![Untitled](https://user-images.githubusercontent.com/244946/163325918-f05b437e-68a3-4eba-923d-dc637e9837cd.jpg)

Adding a *.dmg suffix does not help

**Desktop OS**
- OS: MacOS
- Version: 12.3.1

**Comment by tdiesler** [comment]
`cargo install --git https://github.com/animo/aries-cli` works

**Comment by morrieinmaas** [comment]
Hi @tdiesler, good to hear people are starting to use our tool. How have you tried using `apple-x86_64-aries-cli`? Have you downloaded it from the release page? This works for me. How are you trying to run it? 

I just (re)tried using the downloaded version and that works for me. You may have to go to system settings and allow running it in (under 'Security and Privacy' in System Settings). And you may have to run `sudo chmod +x apple-x86_64-aries-cli` in the containing folder. Then you can run `./apple-x86_64-aries-cli` in your shell (in the containing folder) and/or add it to your path or create and alias to have it available in other location.

**Comment by tdiesler** [comment]
Silly me - I assumed this was an installer instead of the aries-cli binary. This works ...

```
$ chmod +x apple-x86_64-aries-cli 
$ ./apple-x86_64-aries-cli 
```

Wondering whether/how this can be improved?

**Comment by blu3beri** [comment]
@tdiesler Just a quick note, run the following command to move it to your local scripts so that you can just run `aries-cli` instead of `./apple-x86_64-aries-cli`

```sh
cd <the-path-where apple-x86_64-aries-cli-is-installed>
sudo mv apple-x86_64-aries-cli /usr/local/bin/aries-cli
```

Hope that helps :)
