### ISSUE TITLE
Add support for dropping environments from the config

### ISSUE THREAD

**Issue by tdiesler** [animo/aries-cli#165]
**Describe your new idea or enhancement**

```
aries-cli configuration [add|drop|view]
```

'add' can currently be used to update a config. Perhaps being explicit about it is also a good idea.

**Comment by blu3beri** [comment]
Yes the docs should reflect that. 

Drop would be also a good addition. Just wondering about the naming. Wouldnt `remove` make more sense?

**Comment by tdiesler** [comment]
Sure `remove` works just as well
