### ISSUE TITLE
Jazzing up the README.md

### ISSUE THREAD

**Issue by jl-animo** [animo/aries-cli#65]
Let's give the README.md some love. Happy to convert this to a PR, but just wanted to discuss first. The main thing that I think would be cool is to keep the README.md as short as possible and only place salient information there, link to sub-docs for very verbose or detailed explanations.

Here are some ideas about how it might work:

-----------

# insert logo

# Aries CLI

## list code cov, ci and any other badges

The Aries-CLI is the most convenient way for self-sovereign identity (SSI) developers to interact with SSI agents.

Building an SSI solution requires many, _many_ interactions with an SSI agent. Each interaction, often comprised of multiple steps, must be furnished with an endpoint and associated data. The Aries CLI provides for each of these needs by giving users:

* 🌐 **Environments** to easily manage configuration for multiple projects and agents
* ⭐ **Actions** that you can perform against an agent (see our [support matrix](linky))
* 💅🏻 **Mock data** so that you can focus on the important task of building your application instead of other foobar

## Installation
(keeping this part as short as possible, list recommended routes prominently)
### macOS

```sh
brew install aries-cli
```

[Download the binary](linky) and place it on your path.

### Linux

[Download the binary](linky) and place it on your path.

### Windows

[Download the binary](linky) and place it on your path (or whatever steps Windows might require)

#### Advanced installation

See [this document](linky) for advanced installation options.

## Setting up your environment

insert details

### Descriptive name for example

insert details

### Another descriptive name for example

insert details

## Contributing

Is there something you'd like to fix or add to the CLI? Great! We 💗 community contributions.

See the [contributions doc](linky).

### agent-version

| Action | Status | Description |
|---------|--------|------------|
| `action`  | ✅ Available | description |
|  `action-2` | 🚧 Coming soon  | description |

**Comment by jloleysens** [comment]
https://github.com/animo/aries-cli/pull/107
